services:
  nodebackend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"   
    depends_on:
      - db
  db:
    volumes:
      - slack_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017" 
volumes:
   slack_db: